name: Build and test

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

env:
  CARGO_TERM_COLOR: always
  # PKG_CONFIG_PATH: /usr/local/lib/pkgconfig
  # LD_LIBRARY_PATH: /usr/local/lib

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libwayland-dev libgtk-4-dev build-essential gobject-introspection libgirepository1.0-dev gtk-doc-tools python3 valac
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
